const $=s=>document.querySelector(s);let token=localStorage.getItem('token');let current=null;
async function api(path,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(path,opts);if(r.status===401&&path!='/api/auth/login'){logout();throw new Error('Sessão expirada');}const t=await r.text();let d=t?JSON.parse(t):null;if(!r.ok)throw new Error(d?.message||`Erro ${r.status}`);return d}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='';try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});token=d.token;localStorage.setItem('token',token);await boot()}catch(err){$('#loginMsg').textContent=err.message}}
$('#logout').onclick=logout;function logout(){localStorage.removeItem('token');token=null;current=null;$('#app').classList.add('hidden');$('#logout').classList.add('hidden');$('#loginCard').classList.remove('hidden')}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
async function boot(){if(!token)return;try{current=await api('/api/auth/me');$('#loginCard').classList.add('hidden');$('#app').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#welcome').textContent=`Olá, ${current.name}`;$('#role').textContent=`Perfil: ${current.role}`;if(current.role==='Aluno')await student();if(current.role==='Professor')await professor();if(current.role==='Administrador')await admin()}catch{logout()}}
async function student(){const profile=await api('/api/alunos/me');const grades=await api('/api/alunos/me/notas');$('#content').innerHTML=`<div class="grid"><div class="metric">RA<b>${profile.registrationNumber}</b></div><div class="metric">Curso<b style="font-size:18px">${profile.course}</b></div><div class="metric">Disciplinas<b>${grades.length}</b></div><div class="metric">Média<b>${grades.length?(grades.reduce((a,x)=>a+(x.nota||0),0)/grades.length).toFixed(1):'-'}</b></div></div><div class="card section"><h2>Minhas notas</h2>${table(['Código','Disciplina','Semestre','Nota'],grades.map(x=>`<tr><td>${x.codigo}</td><td>${x.disciplina}</td><td>${x.semester}</td><td><b>${x.nota??'-'}</b></td></tr>`))}</div>`}
async function professor(){const classes=await api('/api/professores/me/turmas');const students=await api('/api/professores/me/alunos');$('#content').innerHTML=`<div class="grid"><div class="metric">Turmas<b>${classes.length}</b></div><div class="metric">Alunos vinculados<b>${students.length}</b></div></div><div class="card section"><h2>Turmas</h2>${table(['Código','Disciplina','Semestre','Alunos'],classes.map(x=>`<tr><td>${x.code}</td><td>${x.disciplina}</td><td>${x.semester}</td><td>${x.alunos}</td></tr>`))}</div><div class="card section"><h2>Alunos e notas</h2>${table(['Aluno','RA','Disciplina','Nota'],students.map(x=>`<tr><td>${x.aluno}</td><td>${x.ra}</td><td>${x.disciplina}</td><td>${x.nota??'-'}</td></tr>`))}</div>`}
async function admin(){const [s,u,l,i]=await Promise.all([api('/api/admin/resumo'),api('/api/admin/usuarios'),api('/api/admin/logs?limit=30'),api('/api/admin/incidentes')]);$('#content').innerHTML=`<div class="grid"><div class="metric">Usuários<b>${s.usuarios}</b></div><div class="metric">Falhas / 15 min<b>${s.loginsFalhosUltimos15Min}</b></div><div class="metric">Incidentes abertos<b>${s.incidentesAbertos}</b></div><div class="metric">Eventos hoje<b>${s.eventosSegurancaHoje}</b></div></div><div class="card section"><h2>Usuários</h2>${table(['Nome','E-mail','Perfil','Status'],u.map(x=>`<tr><td>${x.name}</td><td>${x.email}</td><td>${x.role}</td><td><span class="badge ${x.lockedUntilUtc?'danger':'ok'}">${x.lockedUntilUtc?'Bloqueado':'Ativo'}</span></td></tr>`))}</div><div class="card section"><h2>Incidentes</h2>${table(['Tipo','Gravidade','Status','Origem'],i.map(x=>`<tr><td>${x.type}</td><td>${x.severity}</td><td>${x.status}</td><td>${x.source}</td></tr>`))}</div><div class="card section"><h2>Logs de segurança</h2>${table(['Evento','Usuário','IP','Data'],l.map(x=>`<tr><td>${x.eventType}</td><td>${x.userEmail||'-'}</td><td>${x.ipAddress||'-'}</td><td>${new Date(x.createdAtUtc).toLocaleString()}</td></tr>`))}</div>`}
boot();
